### ISSUE TITLE
Push notifications are not working for iOS 13 operating system

### ISSUE THREAD

**Issue by avramanaareddy** [Azure/azure-notificationhubs-java-backend#47] opened 2019-10-18 17:47 UTC
I am working on the background application to send notification to apple devices that are upgraded to the iOS version 13.1.2. 

The notifications  are perfectly sent to iOS 12 version but not to iOS version 13.

 I have added the following statements as per the suggestions given in the stackoverflow website
 notification.headers.put("apns-push-type", "alert");
        notification.headers.put("apns-priority", "5");

Can you please provide the fix for this?

**Comment by brannon** [comment] 2019-10-22 15:24
Duplicate of #48

**Closed by brannon** 2019-10-22 15:24 UTC
